# Generated by Django 4.1.3 on 2023-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='prod',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prod',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
